Build requirement reporting via ergo-query script

diff --git a/tasks/all-ct b/tasks/all-ct
--- a/tasks/all-ct
+++ b/tasks/all-ct
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 
-set -ex
 PARALLEL=yes
 
 if [ $PARALLEL == "yes" ]; then
+  set -e
   scripts/ergo-filefrom rosters/suite_names.txt tasks/suite-roster
   SUITE_NAMES=$(< rosters/suite_names.txt)
 
@@ -11,11 +11,24 @@ if [ $PARALLEL == "yes" ]; then
     scripts/filefrom log/results/$f tasks/tests-ct $f
   done
 
+  FAILS=""
   for f in $SUITE_NAMES; do
-    test -f log/results/$f
-    tail -n 1 log/results/$f | grep -v failed
+    logfile=log/results/$f
+    test -f $logfile
+    if tail -n 1 $logfile | grep -q failed; then
+      FAILS="$FAILS $logfile"
+    fi
   done
+
+  if [ ! -z $FAILS ]; then
+    echo "Failing common test logs: " $FAILS
+    for f in $FAILS; do
+      echo $f
+    done
+    exit 1
+  fi
 else
+  set -ex
   PROJECT=ergo
   ergo-taskfile --requires tasks/rosters/suite_names.txt
   ergo-taskfile --produces tasks/rosters/suite_names.txt --task tasks/suite-roster
@@ -51,4 +64,3 @@ else
     -dir test -logdir logs \
     ${CT_OPTS}
 fi
-
diff --git a/tasks/tests-ct b/tasks/tests-ct
--- a/tasks/tests-ct
+++ b/tasks/tests-ct
@@ -7,9 +7,6 @@ SUITE_NAME=${1:?$(ergo-task-invalid Missing argument 1 \(the suite to test\))}
 SUITE=${SUITE_NAME}_SUITE
 RESULTS=log/results/$SUITE_NAME
 
-#ergo-dep -af tasks/deps
-#ergo-dep -af tasks/build-ct-suites
-
 scripts/requires-all-compiled $0 "$@"
 scripts/filefrom ebin/${PROJECT}.app tasks/app
 scripts/filefrom test/${SUITE_NAME}_SUITE.beam tasks/build-ct-suite ${SUITE_NAME}
@@ -23,5 +20,8 @@ ct_run \
   -no_auto_compile -noshell \
   -pa $(realpath ebin) ${DEPS_DIR}/*/ebin \
   -dir test -logdir logs -suite $SUITE \
-  ${CT_OPTS:=} -erl_args -sname $SUITE_NAME | tee $RESULTS || echo "failed" >> $RESULTS
+  ${CT_OPTS:=} -erl_args -sname $SUITE_NAME | tee $RESULTS
 
+if [ ${PIPESTATUS[0]} -ne 0 ]; then
+  echo "failed" >> $RESULTS
+fi
